# One-to-Many and Many-to-Many Joins - Lab

## Introduction

In this lab, you'll practice your knowledge of one-to-many and many-to-many relationships!

## Objectives

You will be able to:

* Explain one-to-many and many-to-many joins as well as implications for the size of query results
* Query data using one-to-many and many-to-many joins

## One-to-Many and Many-to-Many Joins
<img src='https://curriculum-content.s3.amazonaws.com/data-science/images/Database-Schema.png' width="600">

## Connect to the Database

Include the relevant imports, then connect to the database located at `data.sqlite`.

In [6]:
# Your code here
import sqlite3
import pandas as pd

In [8]:
con=sqlite3.connect("data.sqlite")

In [9]:
cur=con.cursor

## Employees and Their Offices (a One-to-One Join)

Select all of the employees including their first name and last name along with the city and state of the office that they work out of (if they have one). Include all employees and order them by their first name, then their last name.

In [10]:
# Your code here
q='''SELECT e.firstName, e.lastName, o.city,o.state FROM employees e 
     JOIN offices o ON e.officeCode=o.officeCode  
     ORDER BY e.firstName, e.lastName'''
pd.read_sql(q,con)

   firstName   lastName           city       state
0       Andy     Fixter         Sydney
1    Anthony        Bow  San Francisco          CA
2      Barry      Jones         London
3      Diane     Murphy  San Francisco          CA
4   Foon Yue      Tseng            NYC          NY
5     George     Vanauf            NYC          NY
6     Gerard     Bondur          Paris
7     Gerard  Hernandez          Paris
8       Jeff   Firrelli  San Francisco          CA
9      Julie   Firrelli         Boston          MA
10     Larry       Bott         London
11    Leslie   Jennings  San Francisco          CA
12    Leslie   Thompson  San Francisco          CA
13      Loui     Bondur          Paris
14      Mami      Nishi          Tokyo  Chiyoda-Ku
15    Martin     Gerard          Paris
16      Mary  Patterson  San Francisco          CA
17    Pamela   Castillo          Paris
18     Peter      Marsh         Sydney
19     Steve  Patterson         Boston          MA
20       Tom       King         Sydney
21   William  Patterson         Sydney
22   Yoshimi       Kato          Tokyo  Chiyoda-Ku

## Customers and Their Orders (a One-to-Many Join)

Select all of the customer contacts (first and last names) along with details for each of the customers' order numbers, order dates, and statuses.

In [11]:

q='''SELECT c.contactLastName,c.contactFirstName, o.orderNumber, o.orderDate, o.status FROM customers c
     JOIN orders o USING(customerNumber)'''
pd.read_sql(q,con)

    contactLastName contactFirstName  orderNumber   orderDate     status
0           Schmitt          Carine         10123  2003-05-20    Shipped
1           Schmitt          Carine         10298  2004-09-27    Shipped
2           Schmitt          Carine         10345  2004-11-25    Shipped
3              King             Jean        10124  2003-05-21    Shipped
4              King             Jean        10278  2004-08-06    Shipped
..              ...              ...          ...         ...        ...
321          Franco          Valarie        10243  2004-04-26    Shipped
322         Snowden             Tony        10138  2003-07-07    Shipped
323         Snowden             Tony        10179  2003-11-11  Cancelled
324         Snowden             Tony        10360  2004-12-16    Shipped
325         Snowden             Tony        10399  2005-04-01    Shipped

[326 rows x 5 columns]

## Customers and Their Payments (Another One-to-Many Join)

Select all of the customer contacts (first and last names) along with details for each of the customers' payment amounts and date of payment. Sort these results in descending order by the payment amount.

In [12]:
q='''SELECT c.contactLastName,c.contactFirstName, p.amount, p.paymentDate FROM customers c
     JOIN payments p USING(customerNumber)'''
pd.read_sql(q,con)

    contactLastName contactFirstName    amount paymentDate
0           Schmitt          Carine   14571.44  2003-06-05
1           Schmitt          Carine    6066.78  2004-10-19
2           Schmitt          Carine    1676.14  2004-12-18
3              King             Jean  32641.98  2003-06-06
4              King             Jean  33347.88  2004-08-20
..              ...              ...       ...         ...
268          Franco          Valarie  59265.14  2003-12-26
269          Franco          Valarie   6276.60  2004-05-14
270         Snowden             Tony  32077.44  2003-07-16
271         Snowden             Tony  52166.00  2004-12-31
272         Snowden             Tony  30253.75  2005-05-25

[273 rows x 4 columns]

## Orders, Order Details, and Product Details (a Many-to-Many Join)

Select all of the customer contacts (first and last names) along with the product names, quantities, and date ordered for each of the customers and each of their orders. Sort these in descending order by the order date.

> Note: This will require joining 4 tables! This can be tricky! Give it a shot, and if you're still stuck, turn to the next section where you'll see how to write subqueries that can make complex queries such as this much simpler!

In [15]:
q='''SELECT c.contactLastName,c.contactFirstName, pd.productName, pd.quantityInStock, o.orderDate FROM customers c
     JOIN orders o USING(customerNumber)
     JOIN orderdetails od USING(orderNumber)
     JOIN products pd USING(productCode)'''
pd.read_sql(q,con)

,contactLastName,contactFirstName,productName,quantityInStock,orderDate
0,Schmitt,Carine,1965 Aston Martin DB5,9042,2003-05-20
1,Schmitt,Carine,1999 Indy 500 Monte Carlo SS,8164,2003-05-20
2,Schmitt,Carine,1948 Porsche Type 356 Roadster,8990,2003-05-20
3,Schmitt,Carine,1966 Shelby Cobra 427 S/C,8197,2003-05-20
4,Schmitt,Carine,1996 Moto Guzzi 1100i,6625,2004-09-27
...,...,...,...,...,...
2991,Snowden,Tony,2002 Suzuki XREO,9997,2005-04-01
2992,Snowden,Tony,1936 Harley Davidson El Knucklehead,4357,2005-04-01
2993,Snowden,Tony,1997 BMW R 1100 S,7003,2005-04-01
2994,Snowden,Tony,1960 BSA Gold Star DBD34,15,2005-04-01
2995,Snowden,Tony,1997 BMW F650 ST,178,2005-04-01

## Summary

In this lab, you practiced your knowledge of one-to-many and many-to-many relationships!